[build]
  base = "website/"
  publish = "website/dist/"
  command = "npm run build --verbose; cat /opt/buildhome/.npm/_logs/*.log"
[build.processing]
  skip_processing = true

[template]
[template.environment]
  TITLE = "Status"
  KVDB_URL = "https://ya.ru"
