[build]
  base = "website/"
  publish = "website/dist/"
  command = "npm run build"
[build.processing]
  skip_processing = true

[template]
[template.environment]
  TITLE = "Set your site title here. I am required."
  KVDB_URL = "Set the URL to your kvdb bucket with the key suffix. I am required."
