[build]
  base = "website/"
  publish = "website/dist/"
  command = "npm run build"
[build.processing]
  skip_processing = true

[template]
[template.environment]
  TITLE = "Status"
  KVDB_URL = "https://www.ya.ru/"
